/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'site-settings': SiteSetting;
    products: Product;
    variants: Variant;
    categories: Category;
    'attribute-sets': AttributeSet;
    brands: Brand;
    'product-documents': ProductDocument;
    media: Media;
    pages: Page;
    navigation: Navigation;
    banners: Banner;
    dealers: Dealer;
    enquiries: Enquiry;
    'shipping-zones': ShippingZone;
    orders: Order;
    'order-events': OrderEvent;
    transactions: Transaction;
    refunds: Refund;
    invoices: Invoice;
    shipments: Shipment;
    carts: Cart;
    'stock-movements': StockMovement;
    'idempotency-keys': IdempotencyKey;
    pincodes: Pincode;
    counters: Counter;
    'connector-configs': ConnectorConfig;
    tenants: Tenant;
    'tenant-domains': TenantDomain;
    plans: Plan;
    subscriptions: Subscription;
    'feature-flags': FeatureFlag;
    users: User;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'attribute-sets': AttributeSetsSelect<false> | AttributeSetsSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    'product-documents': ProductDocumentsSelect<false> | ProductDocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    dealers: DealersSelect<false> | DealersSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'shipping-zones': ShippingZonesSelect<false> | ShippingZonesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-events': OrderEventsSelect<false> | OrderEventsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    shipments: ShipmentsSelect<false> | ShipmentsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'idempotency-keys': IdempotencyKeysSelect<false> | IdempotencyKeysSelect<true>;
    pincodes: PincodesSelect<false> | PincodesSelect<true>;
    counters: CountersSelect<false> | CountersSelect<true>;
    'connector-configs': ConnectorConfigsSelect<false> | ConnectorConfigsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-domains': TenantDomainsSelect<false> | TenantDomainsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'feature-flags': FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'tenancy-check-subscriptions': TaskTenancyCheckSubscriptions;
      'payments-reconcile': TaskPaymentsReconcile;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  tenant?: (string | null) | Tenant;
  storeName: string;
  /**
   * Used for the phone app bar
   */
  themeColor?: string | null;
  logo?: (string | null) | Media;
  logoDark?: (string | null) | Media;
  favicon?: (string | null) | Media;
  /**
   * Shown when shoppers install the store on their phone
   */
  pwaIcon?: (string | null) | Media;
  contact?: {
    email?: string | null;
    phone?: string | null;
    /**
     * Used by the WhatsApp button
     */
    whatsapp?: string | null;
    address?: string | null;
  };
  social?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
  };
  grievanceOfficer?: {
    name?: string | null;
    designation?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  legalDefaults?: {
    manufacturerName?: string | null;
    manufacturerAddress?: string | null;
    consumerCare?: string | null;
  };
  /**
   * Set at onboarding, for example AQV for AQV-10482
   */
  orderPrefix: string;
  invoice?: {
    /**
     * Up to 4 capital letters or digits: INV/26-27/00123 stays within GST’s 16 characters
     */
    prefix?: string | null;
    authorisedSignatory?: string | null;
    signature?: (string | null) | Media;
    footerNote?: string | null;
  };
  /**
   * Cash on delivery rules are set on the Payments screen.
   */
  checkout?: {
    minOrderValue?: Money;
    codEnabled?: boolean | null;
    codMinOrder?: Money;
    codMaxOrder?: Money;
    codFee?: Money;
  };
  returns?: {
    windowDays?: number | null;
    exchangeOnly?: boolean | null;
  };
  announcementBar?: {
    enabled?: boolean | null;
    text?: string | null;
    linkUrl?: string | null;
  };
  policies?: {
    shipping?: (string | null) | Page;
    returns?: (string | null) | Page;
    privacy?: (string | null) | Page;
    terms?: (string | null) | Page;
    warranty?: (string | null) | Page;
  };
  seoDefaults?: {
    /**
     * %s is replaced by the page name, for example “%s · Aquaverde”
     */
    titleTemplate?: string | null;
    ogImage?: (string | null) | Media;
  };
  /**
   * Loaded only after the shopper accepts analytics cookies.
   */
  analytics?: {
    ga4Id?: string | null;
    metaPixelId?: string | null;
    gtmId?: string | null;
  };
  maintenanceMode?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  legalName: string;
  /**
   * PAN and state fill in from the GSTIN
   */
  gstin?: string | null;
  /**
   * From the GSTIN when there is one
   */
  pan?: string | null;
  /**
   * Same state: CGST + SGST. Other states: IGST
   */
  stateCode?:
    | (
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '26'
        | '27'
        | '29'
        | '30'
        | '31'
        | '32'
        | '33'
        | '34'
        | '35'
        | '36'
        | '37'
        | '38'
        | '97'
        | '01'
        | '02'
        | '03'
        | '04'
        | '05'
        | '06'
        | '07'
        | '08'
        | '09'
      )
    | null;
  registeredAddress?: PostalAddress;
  industry: ('sanitary' | 'locks' | 'hardware' | 'decor' | 'clothing' | 'other')[];
  supportEmail?: string | null;
  supportPhone?: string | null;
  whatsappNumber?: string | null;
  /**
   * Permanent. Names the subdomain and the vendor UI folder in code (src/storefront/vendors/<slug>).
   */
  slug: string;
  /**
   * More languages in Phase 2
   */
  defaultLocale?: 'en' | null;
  /**
   * Fixed to INR in the MVP
   */
  currency?: 'INR' | null;
  timezone?: 'Asia/Kolkata' | null;
  enabledLocales?: 'en'[] | null;
  /**
   * Visible to our team only. For example: prefers WhatsApp, renewal call in March.
   */
  notes?: string | null;
  /**
   * Changed with Go live, Suspend and Resume above
   */
  status: 'draft' | 'active' | 'suspended' | 'archived';
  /**
   * Changed from the Billing tab
   */
  plan: string | Plan;
  usage?: {
    productsCount?: number | null;
    staffCount?: number | null;
    storageBytes?: number | null;
    ordersThisMonth?: number | null;
    updatedAt?: string | null;
  };
  enabledFeatures?:
    | (
        | 'guest-checkout'
        | 'cod-confirmation'
        | 'cod'
        | 'enquiries'
        | 'appointments'
        | 'enquire-only-products'
        | 'downloads'
        | 'size-guide'
        | 'product-videos'
        | 'compare'
        | 'dealer-locator'
        | 'whatsapp-button'
        | 'multilingual'
        | 'lookbook'
        | 'blog'
        | 'pincode-check'
        | 'schemes'
        | 'coupons'
        | 'trade-schemes'
        | 'wishlist'
        | 'reviews'
        | 'offer-messages'
        | 'whatsapp-offers'
        | 'push-notifications'
        | 'abandoned-cart'
        | 'affiliate'
        | 'warranty'
        | 'service-requests'
        | 'installation-booking'
        | 'spare-parts'
        | 'b2b'
        | 'loyalty'
      )[]
    | null;
  blockedConnectors?: ('razorpay' | 'manual' | 'shiprocket' | 'meta-whatsapp' | 'msg91')[] | null;
  dbRef?: string | null;
  createdBy?: (string | null) | User;
  activatedAt?: string | null;
  presetAppliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostalAddress".
 */
export interface PostalAddress {
  line1?: string | null;
  line2?: string | null;
  city?: string | null;
  stateCode?:
    | (
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '26'
        | '27'
        | '29'
        | '30'
        | '31'
        | '32'
        | '33'
        | '34'
        | '35'
        | '36'
        | '37'
        | '38'
        | '97'
        | '01'
        | '02'
        | '03'
        | '04'
        | '05'
        | '06'
        | '07'
        | '08'
        | '09'
      )
    | null;
  pincode?: string | null;
}
/**
 * A plan is a ceiling, not a switch: features in a plan stay off until switched on per vendor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string;
  name: string;
  /**
   * Short permanent key, for example starter
   */
  code: string;
  priceMonthly: Money;
  priceYearly?: Money;
  /**
   * Optional. A new subscription’s first payment covers these months at this price (before GST); then the monthly price applies. Example: ₹9,999 for 3 months.
   */
  introOffer?: {
    price?: Money;
    months?: number | null;
  };
  /**
   * Checked on the server. Stores are warned at 90% of a limit.
   */
  limits: {
    maxProducts: number;
    maxStaffUsers: number;
    maxStorageGB: number;
    /**
     * Empty means no limit
     */
    maxOrdersPerMonth?: number | null;
  };
  allowedModules?:
    | (
        | 'guest-checkout'
        | 'cod-confirmation'
        | 'cod'
        | 'enquiries'
        | 'appointments'
        | 'enquire-only-products'
        | 'downloads'
        | 'size-guide'
        | 'product-videos'
        | 'compare'
        | 'dealer-locator'
        | 'whatsapp-button'
        | 'multilingual'
        | 'lookbook'
        | 'blog'
        | 'pincode-check'
        | 'schemes'
        | 'coupons'
        | 'trade-schemes'
        | 'wishlist'
        | 'reviews'
        | 'offer-messages'
        | 'whatsapp-offers'
        | 'push-notifications'
        | 'abandoned-cart'
        | 'affiliate'
        | 'warranty'
        | 'service-requests'
        | 'installation-booking'
        | 'spare-parts'
        | 'b2b'
        | 'loyalty'
      )[]
    | null;
  allowedConnectors?: ('razorpay' | 'manual' | 'shiprocket' | 'meta-whatsapp' | 'msg91')[] | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Money".
 */
export interface Money {
  amountMinor?: number | null;
  currency?: 'INR' | null;
}
/**
 * Everyone who signs in to the admin: our team and every store’s staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone?: string | null;
  /**
   * Our team only. Leave empty for vendor staff.
   */
  platformRole?: ('super-admin' | 'support') | null;
  status: 'invited' | 'active' | 'disabled';
  lastLoginAt?: string | null;
  invitedBy?: (string | null) | User;
  invitedAt?: string | null;
  storeSession?: {
    tenant?: (string | null) | Tenant;
    mode?: ('manage' | 'view') | null;
    reason?: string | null;
    startedAt?: string | null;
    endsAt?: string | null;
  };
  tenants?:
    | {
        tenant: string | Tenant;
        roles: ('owner' | 'manager' | 'catalog-editor' | 'order-manager' | 'content-editor' | 'support')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos and PDFs. Images are resized for phones and desktops automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  tenant?: (string | null) | Tenant;
  /**
   * Describe the photo for people using screen readers and for search engines, for example “Aria basin mixer in matt black, side view”.
   */
  alt?: string | null;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Versions are kept for every save. Policy pages are linked from the footer and checkout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  tenant?: (string | null) | Tenant;
  title: string;
  layout?:
    | (
        | HeroBlock
        | BannerBlock
        | BenefitsBlock
        | TestimonialsBlock
        | BrandStoryBlock
        | ProductGridBlock
        | CategoryTilesBlock
        | DownloadsBlock
        | RichTextBlock
        | ImageTextBlock
        | VideoBlock
        | FaqBlock
        | DealerFinderBlock
        | EnquiryFormBlock
      )[]
    | null;
  seo?: Seo;
  template: 'default' | 'landing' | 'policy';
  /**
   * Filled from the title. Store address: /pages/<slug>. The home page uses “home”.
   */
  slug?: string | null;
  publishedAt?: string | null;
  lastEditedBy?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  slides: {
    image: string | Media;
    /**
     * A separate, smaller image keeps the first screen fast on phones
     */
    mobileImage?: (string | null) | Media;
    heading: string;
    subheading?: string | null;
    buttonLabel?: string | null;
    buttonLink?: Link;
    id?: string | null;
  }[];
  autoplay?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link".
 */
export interface Link {
  type?: ('page' | 'category' | 'product' | 'url') | null;
  page?: (string | null) | Page;
  category?: (string | null) | Category;
  product?: (string | null) | Product;
  url?: string | null;
  newTab?: boolean | null;
}
/**
 * Menus and category tiles follow the sort order (low numbers first).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  /**
   * Filled from the name. Store address: /c/<parent>/<slug>
   */
  slug?: string | null;
  /**
   * Specification fields and filters here. Empty: the parent’s set
   */
  attributeSet?: (string | null) | AttributeSet;
  image?: (string | null) | Media;
  banner?: (string | null) | Media;
  description?: string | null;
  /**
   * Shown as “Size guide” on products in this category
   */
  sizeChart?: (string | null) | Media;
  isVisible?: boolean | null;
  sortOrder?: number | null;
  seo?: Seo;
  /**
   * Empty for a top-level category
   */
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Specification fields per kind of product. “Filter” adds it to the store’s filters; “Variant option” makes each value its own SKU.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-sets".
 */
export interface AttributeSet {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  attributes?:
    | {
        label: string;
        /**
         * Filled from the label if empty. Don’t change it later
         */
        code?: string | null;
        type: 'text' | 'number' | 'select' | 'multiselect' | 'boolean' | 'color';
        unit?: string | null;
        /**
         * Section on the product page
         */
        group?: string | null;
        isFilterable?: boolean | null;
        isVariantAxis?: boolean | null;
        isComparable?: boolean | null;
        isRequired?: boolean | null;
        options?:
          | {
              label: string;
              value?: string | null;
              swatchHex?: string | null;
              swatchImage?: (string | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Leave empty to use the name and the store’s defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Seo".
 */
export interface Seo {
  title?: string | null;
  description?: string | null;
  image?: (string | null) | Media;
}
/**
 * Products need a main category: it decides the specification fields.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  tenant?: (string | null) | Tenant;
  title: string;
  modelNumber: string;
  /**
   * Decides the specification fields
   */
  primaryCategory: string | Category;
  categories?: (string | Category)[] | null;
  brand?: (string | null) | Brand;
  shortDescription?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The first photo is the main one
   */
  gallery?: (string | Media)[] | null;
  videos?:
    | {
        url: string;
        type?: ('installation' | 'demo' | 'promo') | null;
        id?: string | null;
      }[]
    | null;
  attributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  price?: Money;
  compareAtPrice?: Money;
  gstRate?: ('0' | '0.25' | '3' | '5' | '18' | '40') | null;
  hsnCode?: string | null;
  weightGrams?: number | null;
  dimensions?: {
    lengthMm?: number | null;
    widthMm?: number | null;
    heightMm?: number | null;
  };
  legal?: {
    genericName?: string | null;
    netQuantity?: string | null;
    countryOfOrigin?: string | null;
    madeBy?: ('manufacturer' | 'packer' | 'importer') | null;
    madeByName?: string | null;
    madeByAddress?: string | null;
    consumerCare?: string | null;
  };
  documents?: (string | ProductDocument)[] | null;
  relatedProducts?: (string | Product)[] | null;
  /**
   * Filled from the title. Store address: /products/<slug>
   */
  slug?: string | null;
  /**
   * Other words shoppers use, separated by commas
   */
  searchKeywords?: string | null;
  seo?: Seo;
  status: 'draft' | 'active' | 'archived';
  /**
   * Online checkout arrives in stage B; until then every product shows “Request a quote”.
   */
  purchaseMode: 'buy' | 'enquire' | 'both';
  isFeatured?: boolean | null;
  lastEditedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only needed when the store sells under more than one brand name.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  /**
   * Filled from the name
   */
  slug?: string | null;
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Usually created from a product’s “Finishes and sizes” tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  tenant?: (string | null) | Tenant;
  product: string | Product;
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Filled from the model number and options if empty
   */
  sku?: string | null;
  /**
   * From the options
   */
  title?: string | null;
  barcode?: string | null;
  price?: Money;
  compareAtPrice?: Money;
  /**
   * Photos of this finish. Empty: the product’s photos
   */
  images?: (string | Media)[] | null;
  stockQty?: number | null;
  reservedQty?: number | null;
  lowStockThreshold?: number | null;
  weightGrams?: number | null;
  allowBackorder?: boolean | null;
  status: 'active' | 'inactive';
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-documents".
 */
export interface ProductDocument {
  id: string;
  tenant?: (string | null) | Tenant;
  title: string;
  type:
    'spec-sheet' | 'installation-manual' | 'brochure' | 'catalogue' | 'price-list' | 'warranty-card' | 'certificate';
  file: string | Media;
  /**
   * Groups the document on the Downloads page
   */
  categories?: (string | Category)[] | null;
  showOnDownloadsPage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  image: string | Media;
  mobileImage?: (string | null) | Media;
  heading?: string | null;
  link?: Link;
  layout?: ('full' | 'split') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock".
 */
export interface BenefitsBlock {
  items?:
    | {
        icon?: ('truck' | 'shield' | 'badge' | 'return' | 'phone' | 'check') | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'benefits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  /**
   * Real quotes from real customers or partners only (docs/14). Product ratings come from the Reviews block, never typed here.
   */
  items?:
    | {
        quote: string;
        name: string;
        place?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandStoryBlock".
 */
export interface BrandStoryBlock {
  heading?: string | null;
  text?: string | null;
  image?: (string | null) | Media;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brandStory';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock".
 */
export interface ProductGridBlock {
  heading?: string | null;
  source: 'featured' | 'newest' | 'bestsellers' | 'category';
  category?: (string | null) | Category;
  limit?: number | null;
  layout?: ('grid' | 'carousel') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'productGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryTilesBlock".
 */
export interface CategoryTilesBlock {
  heading?: string | null;
  categories: (string | Category)[];
  style?: ('tiles' | 'circles') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'categoryTiles';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadsBlock".
 */
export interface DownloadsBlock {
  heading?: string | null;
  documentType?: ('catalogue' | 'brochure' | 'price-list' | 'all') | null;
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'downloads';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock".
 */
export interface ImageTextBlock {
  image: string | Media;
  heading?: string | null;
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imageSide?: ('left' | 'right') | null;
  buttonLabel?: string | null;
  buttonLink?: Link;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  heading?: string | null;
  youtubeUrl: string;
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'video';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DealerFinderBlock".
 */
export interface DealerFinderBlock {
  heading?: string | null;
  text?: string | null;
  buttonLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dealerFinder';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnquiryFormBlock".
 */
export interface EnquiryFormBlock {
  heading?: string | null;
  text?: string | null;
  enquiryType?: ('general' | 'bulk' | 'project' | 'dealership') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'enquiryForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  tenant?: (string | null) | Tenant;
  title?: string | null;
  header?:
    | {
        label: string;
        link?: Link;
        /**
         * Optional. Up to four columns open under this item on desktop.
         */
        columns?:
          | {
              heading?: string | null;
              links?:
                | {
                    label: string;
                    link?: Link;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        featuredImage?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              link?: Link;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Switch off to set a shorter menu for phones.
   */
  mobileSameAsHeader?: boolean | null;
  mobile?:
    | {
        label: string;
        link?: Link;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: string;
  tenant?: (string | null) | Tenant;
  /**
   * For staff only
   */
  title: string;
  placement: 'home-hero' | 'category-top' | 'announcement' | 'popup';
  image: string | Media;
  mobileImage?: (string | null) | Media;
  link?: Link;
  startsAt?: string | null;
  endsAt?: string | null;
  /**
   * Higher shows first
   */
  priority?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Only dealers marked “Show on store” appear on the dealer locator.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers".
 */
export interface Dealer {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  type: 'dealer' | 'distributor' | 'showroom' | 'service-centre' | 'experience-centre';
  isActive?: boolean | null;
  address: string;
  city: string;
  state: string;
  pincode: string;
  /**
   * In Google Maps, right-click the shop to copy its latitude and longitude, then enter each in its own box. Dealers without a position are listed but not pinned on the map.
   *
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  phone: string;
  email?: string | null;
  hours?: string | null;
  categories?: (string | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  tenant?: (string | null) | Tenant;
  /**
   * Given on save, shown to the shopper
   */
  referenceNumber?: string | null;
  type: 'product' | 'bulk' | 'project' | 'dealership' | 'general';
  status: 'new' | 'contacted' | 'quoted' | 'won' | 'lost';
  assignedTo?: (string | null) | User;
  productTitle?: string | null;
  modelNumber?: string | null;
  qty?: number | null;
  message?: string | null;
  name: string;
  company?: string | null;
  phone?: string | null;
  email?: string | null;
  city?: string | null;
  pincode?: string | null;
  consentToContact?: boolean | null;
  /**
   * Only your team sees these
   */
  internalNotes?:
    | {
        text: string;
        by?: (string | null) | User;
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  source?: {
    page?: string | null;
    utmSource?: string | null;
    utmMedium?: string | null;
    utmCampaign?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones".
 */
export interface ShippingZone {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  /**
   * Off: shoppers in this zone can’t order (a blocked area)
   */
  isServiceable?: boolean | null;
  sortOrder?: number | null;
  states?:
    | (
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '26'
        | '27'
        | '29'
        | '30'
        | '31'
        | '32'
        | '33'
        | '34'
        | '35'
        | '36'
        | '37'
        | '38'
        | '97'
        | '01'
        | '02'
        | '03'
        | '04'
        | '05'
        | '06'
        | '07'
        | '08'
        | '09'
      )[]
    | null;
  /**
   * Whole pincodes (411045) or their first digits (4110 covers 411001 to 411099)
   */
  pincodePrefixes?: string[] | null;
  rateType: 'flat' | 'weight' | 'order-value';
  fee?: Money;
  freeAbove?: Money;
  baseWeightGrams?: number | null;
  perExtraKg?: Money;
  /**
   * The highest bracket the order reaches applies
   */
  valueBrackets?:
    | {
        from: Money;
        bracketFee: Money;
        id?: string | null;
      }[]
    | null;
  codAllowed?: boolean | null;
  etaMinDays?: number | null;
  etaMaxDays?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  tenant?: (string | null) | Tenant;
  orderNumber: string;
  status: 'pending' | 'confirmed' | 'processing' | 'completed' | 'cancelled';
  paymentStatus: 'pending' | 'authorized' | 'paid' | 'partially_refunded' | 'refunded' | 'failed';
  fulfillmentStatus:
    | 'unfulfilled'
    | 'packed'
    | 'partially_shipped'
    | 'shipped'
    | 'out_for_delivery'
    | 'delivery_failed'
    | 'delivered'
    | 'rto'
    | 'lost'
    | 'returned'
    | 'cancelled';
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  items?:
    | {
        productId?: string | null;
        variantId?: string | null;
        sku?: string | null;
        title: string;
        options?: string | null;
        imageUrl?: string | null;
        qty: number;
        unitMinor?: number | null;
        mrpMinor?: number | null;
        discountMinor?: number | null;
        hsnCode?: string | null;
        gstRate?: number | null;
        taxableMinor?: number | null;
        cgstMinor?: number | null;
        sgstMinor?: number | null;
        igstMinor?: number | null;
        lineTotalMinor?: number | null;
        weightGrams?: number | null;
        id?: string | null;
      }[]
    | null;
  charges?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totals?: {
    itemsMinor?: number | null;
    discountMinor?: number | null;
    subtotalMinor?: number | null;
    shippingMinor?: number | null;
    codFeeMinor?: number | null;
    taxableMinor?: number | null;
    cgstMinor?: number | null;
    sgstMinor?: number | null;
    igstMinor?: number | null;
    taxMinor?: number | null;
    roundOffMinor?: number | null;
    grandTotalMinor?: number | null;
    paidMinor?: number | null;
    refundedMinor?: number | null;
  };
  shippingAddress?: ShopperAddress;
  billingSameAsShipping?: boolean | null;
  buyerGstin?: string | null;
  buyerLegalName?: string | null;
  billingAddress?: ShopperAddress;
  sellerStateCode?: string | null;
  placeOfSupplyStateCode?: string | null;
  paymentMethod: 'razorpay' | 'cod';
  /**
   * Razorpay test orders charge nobody
   */
  paymentMode?: ('test' | 'live') | null;
  shippingMethod?: {
    source?: ('shiprocket' | 'rate-card') | null;
    zoneName?: string | null;
    courierName?: string | null;
    etaMinDays?: number | null;
    etaMaxDays?: number | null;
  };
  appliedOffers?:
    | {
        kind?: ('scheme' | 'coupon') | null;
        ref?: string | null;
        code?: string | null;
        name?: string | null;
        discountMinor?: number | null;
        id?: string | null;
      }[]
    | null;
  couponCode?: string | null;
  invoice?: (string | null) | Invoice;
  /**
   * The /t/<code> link in messages to the shopper
   */
  trackingCode: string;
  whatsappOptIn?: boolean | null;
  notes?: string | null;
  source?: ('web' | 'pwa' | 'admin') | null;
  locale?: string | null;
  cartId?: string | null;
  placedAt?: string | null;
  confirmedAt?: string | null;
  paidAt?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
  /**
   * An unpaid online order is cancelled after this
   */
  expiresAt?: string | null;
  cancelReason?: string | null;
  stockState?: ('none' | 'reserved' | 'sold' | 'released' | 'restocked') | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopperAddress".
 */
export interface ShopperAddress {
  name?: string | null;
  /**
   * +91 and 10 digits
   */
  phone?: string | null;
  line1?: string | null;
  line2?: string | null;
  landmark?: string | null;
  city?: string | null;
  stateCode?:
    | (
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '26'
        | '27'
        | '29'
        | '30'
        | '31'
        | '32'
        | '33'
        | '34'
        | '35'
        | '36'
        | '37'
        | '38'
        | '97'
        | '01'
        | '02'
        | '03'
        | '04'
        | '05'
        | '06'
        | '07'
        | '08'
        | '09'
      )
    | null;
  pincode?: string | null;
  country?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: string;
  tenant?: (string | null) | Tenant;
  order: string | Order;
  type: 'tax-invoice' | 'credit-note';
  number: string;
  financialYear: string;
  issuedAt: string;
  /**
   * The invoice a credit note corrects
   */
  againstInvoice?: (string | null) | Invoice;
  seller:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  buyer:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  placeOfSupply:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lines:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  totals:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  amountInWords: string;
  /**
   * E-invoicing, later
   */
  irn?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-events".
 */
export interface OrderEvent {
  id: string;
  tenant?: (string | null) | Tenant;
  order: string | Order;
  type:
    | 'created'
    | 'payment_captured'
    | 'payment_failed'
    | 'status_changed'
    | 'parcel_status_changed'
    | 'note'
    | 'refund'
    | 'invoice'
    | 'message_sent'
    | 'shopper_reply';
  text: string;
  from?: string | null;
  to?: string | null;
  byUser?: (string | null) | User;
  /**
   * Who did it when not a staff member: system, shopper, Razorpay…
   */
  byLabel?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  at: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  tenant?: (string | null) | Tenant;
  order: string | Order;
  provider: 'razorpay' | 'cod' | 'manual';
  mode?: ('test' | 'live') | null;
  providerOrderId: string;
  providerPaymentId?: string | null;
  amountMinor: number;
  status: 'created' | 'authorized' | 'captured' | 'failed' | 'refunded' | 'partially_refunded';
  /**
   * upi, card, netbanking, wallet, emi
   */
  method?: string | null;
  /**
   * Bank or card network
   */
  methodDetail?: string | null;
  capturedAt?: string | null;
  failureReason?: string | null;
  refundedMinor?: number | null;
  /**
   * Webhook events already handled
   */
  processedEventIds?: string[] | null;
  /**
   * The last provider payload, without card or contact details
   */
  raw?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: string;
  tenant?: (string | null) | Tenant;
  order: string | Order;
  transaction?: (string | null) | Transaction;
  amountMinor: number;
  reason: string;
  method: 'razorpay' | 'manual';
  providerRefundId?: string | null;
  /**
   * Bank transfer or UPI reference for a manual refund
   */
  reference?: string | null;
  status: 'pending' | 'processed' | 'failed';
  /**
   * Order lines and quantities refunded, when not the whole order
   */
  lines?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  includesShipping?: boolean | null;
  creditNote?: (string | null) | Invoice;
  by?: (string | null) | User;
  processedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments".
 */
export interface Shipment {
  id: string;
  tenant?: (string | null) | Tenant;
  order: string | Order;
  direction: 'forward' | 'return';
  status:
    | 'packed'
    | 'shipped'
    | 'in_transit'
    | 'out_for_delivery'
    | 'delivery_failed'
    | 'delivered'
    | 'rto_initiated'
    | 'rto_delivered'
    | 'cancelled'
    | 'lost';
  items?:
    | {
        orderItemId: string;
        title?: string | null;
        sku?: string | null;
        qty: number;
        id?: string | null;
      }[]
    | null;
  package?: {
    lengthMm?: number | null;
    breadthMm?: number | null;
    heightMm?: number | null;
    weightGrams?: number | null;
  };
  provider?: ('manual' | 'shiprocket') | null;
  carrier?: string | null;
  courierId?: string | null;
  trackingNumber?: string | null;
  trackingUrl?: string | null;
  awb?: string | null;
  providerOrderId?: string | null;
  providerShipmentId?: string | null;
  labelUrl?: string | null;
  pickupScheduledFor?: string | null;
  expectedDeliveryDate?: string | null;
  codAmountMinor?: number | null;
  ewayBillNo?: string | null;
  attempts?: number | null;
  failureReason?: ('customer_unavailable' | 'address_issue' | 'refused' | 'cod_not_ready' | 'other') | null;
  ndrAction?: {
    action?: ('re-attempt' | 'return') | null;
    deferredDate?: string | null;
    note?: string | null;
    by?: (string | null) | User;
    at?: string | null;
  };
  events?:
    | {
        status: string;
        at: string;
        source?: ('staff' | 'shiprocket' | 'import' | 'system') | null;
        by?: (string | null) | User;
        note?: string | null;
        location?: string | null;
        /**
         * Shiprocket: AWB + status + scan time
         */
        dedupeKey?: string | null;
        id?: string | null;
      }[]
    | null;
  packedAt?: string | null;
  shippedAt?: string | null;
  outForDeliveryAt?: string | null;
  deliveredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  tenant?: (string | null) | Tenant;
  tokenHash: string;
  status: 'active' | 'converted' | 'abandoned';
  items?:
    | {
        product: string | Product;
        variant?: (string | null) | Variant;
        qty: number;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  pincode?: string | null;
  shippingAddress?: ShopperAddress;
  couponCode?: string | null;
  lastActivityAt?: string | null;
  convertedOrder?: (string | null) | Order;
  /**
   * Removed 30 days after the last change
   */
  expiresAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: string;
  tenant?: (string | null) | Tenant;
  variant: string | Variant;
  reason: 'reserve' | 'release' | 'sale' | 'cancel' | 'return' | 'adjustment' | 'import';
  stockDelta?: number | null;
  reservedDelta?: number | null;
  order?: (string | null) | Order;
  by?: (string | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys".
 */
export interface IdempotencyKey {
  id: string;
  tenant?: (string | null) | Tenant;
  key: string;
  route: string;
  requestHash: string;
  responseStatus?: number | null;
  responseBody?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pincodes".
 */
export interface Pincode {
  id: string;
  pincode: string;
  city?: string | null;
  district?: string | null;
  stateCode:
    | '10'
    | '11'
    | '12'
    | '13'
    | '14'
    | '15'
    | '16'
    | '17'
    | '18'
    | '19'
    | '20'
    | '21'
    | '22'
    | '23'
    | '24'
    | '26'
    | '27'
    | '29'
    | '30'
    | '31'
    | '32'
    | '33'
    | '34'
    | '35'
    | '36'
    | '37'
    | '38'
    | '97'
    | '01'
    | '02'
    | '03'
    | '04'
    | '05'
    | '06'
    | '07'
    | '08'
    | '09';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counters".
 */
export interface Counter {
  id: string;
  tenant?: (string | null) | Tenant;
  key: string;
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connector-configs".
 */
export interface ConnectorConfig {
  id: string;
  tenant?: (string | null) | Tenant;
  provider: 'razorpay' | 'manual' | 'shiprocket' | 'meta-whatsapp' | 'msg91';
  kind: 'payment' | 'shipping' | 'messaging';
  enabled?: boolean | null;
  mode?: ('test' | 'live') | null;
  /**
   * Safe to show: key IDs, phone number ID, pickup name
   */
  publicConfig?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  secretSealed?: string | null;
  /**
   * Which secrets are saved, never their values
   */
  savedSecrets?: string[] | null;
  webhookToken?: string | null;
  routingKey?: string | null;
  health?: {
    lastTestAt?: string | null;
    lastTestOk?: boolean | null;
    lastTestMessage?: string | null;
    lastWebhookAt?: string | null;
    lastWebhookOkAt?: string | null;
    /**
     * First failure since the last success; cleared when one works
     */
    failingSince?: string | null;
    failedCount?: number | null;
    lastErrorAt?: string | null;
    lastError?: string | null;
    /**
     * Provider facts from the last check (WhatsApp quality, limit)
     */
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  connectedBy?: (string | null) | User;
  connectedAt?: string | null;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-domains".
 */
export interface TenantDomain {
  id: string;
  host: string;
  tenant: string | Tenant;
  type: 'subdomain' | 'custom';
  isPrimary?: boolean | null;
  /**
   * Send visitors on this host to the primary domain (301)
   */
  redirectToPrimary?: boolean | null;
  verifiedAt?: string | null;
  sslStatus?: ('pending' | 'issuing' | 'active' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manual billing in the MVP (automatic with Razorpay Subscriptions in Phase 2).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  tenant: string | Tenant;
  vendorName?: string | null;
  plan: string | Plan;
  status: 'trialing' | 'active' | 'past_due' | 'cancelled' | 'paused';
  billingCycle: 'monthly' | 'yearly';
  billingMode: 'manual' | 'razorpay';
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  trialEndsAt?: string | null;
  providerSubscriptionId?: string | null;
  payments?:
    | {
        amountMinor: number;
        paidOn: string;
        method: 'neft' | 'imps' | 'upi' | 'cheque' | 'card';
        reference?: string | null;
        coversPeriod?: {
          start?: string | null;
          end?: string | null;
        };
        recordedBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  history?:
    | {
        at: string;
        event: string;
        amountMinor?: number | null;
        reference?: string | null;
        by?: (string | null) | User;
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags".
 */
export interface FeatureFlag {
  id: string;
  tenant?: (string | null) | Tenant;
  key:
    | 'guest-checkout'
    | 'cod-confirmation'
    | 'cod'
    | 'enquiries'
    | 'appointments'
    | 'enquire-only-products'
    | 'downloads'
    | 'size-guide'
    | 'product-videos'
    | 'compare'
    | 'dealer-locator'
    | 'whatsapp-button'
    | 'multilingual'
    | 'lookbook'
    | 'blog'
    | 'pincode-check'
    | 'schemes'
    | 'coupons'
    | 'trade-schemes'
    | 'wishlist'
    | 'reviews'
    | 'offer-messages'
    | 'whatsapp-offers'
    | 'push-notifications'
    | 'abandoned-cart'
    | 'affiliate'
    | 'warranty'
    | 'service-requests'
    | 'installation-booking'
    | 'spare-parts'
    | 'b2b'
    | 'loyalty';
  enabled?: boolean | null;
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enabledBy?: (string | null) | User;
  enabledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  tenant?: (string | null) | Tenant;
  actor?: (string | null) | User;
  actorRole?: string | null;
  action:
    | 'support_access'
    | 'store_managed_change'
    | 'store_created'
    | 'store_status_changed'
    | 'store_details_changed'
    | 'feature_changed'
    | 'connector_changed'
    | 'plan_changed'
    | 'plan_edited'
    | 'subscription_payment'
    | 'subscription_status_changed'
    | 'staff_invited'
    | 'staff_changed'
    | 'two_factor_reset'
    | 'domain_changed'
    | 'price_changed'
    | 'refund'
    | 'scheme_changed'
    | 'coupon_changed'
    | 'commission_changed'
    | 'affiliate_payout'
    | 'review_moderated';
  /**
   * One line people can read
   */
  summary?: string | null;
  collectionSlug?: string | null;
  docId?: string | null;
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason?: string | null;
  actingAsPlatform?: boolean | null;
  ip?: string | null;
  at: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'tenancy-check-subscriptions' | 'payments-reconcile' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'tenancy-check-subscriptions' | 'payments-reconcile' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'site-settings';
        value: string | SiteSetting;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'attribute-sets';
        value: string | AttributeSet;
      } | null)
    | ({
        relationTo: 'brands';
        value: string | Brand;
      } | null)
    | ({
        relationTo: 'product-documents';
        value: string | ProductDocument;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'navigation';
        value: string | Navigation;
      } | null)
    | ({
        relationTo: 'banners';
        value: string | Banner;
      } | null)
    | ({
        relationTo: 'dealers';
        value: string | Dealer;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'shipping-zones';
        value: string | ShippingZone;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'order-events';
        value: string | OrderEvent;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'refunds';
        value: string | Refund;
      } | null)
    | ({
        relationTo: 'invoices';
        value: string | Invoice;
      } | null)
    | ({
        relationTo: 'shipments';
        value: string | Shipment;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: string | StockMovement;
      } | null)
    | ({
        relationTo: 'idempotency-keys';
        value: string | IdempotencyKey;
      } | null)
    | ({
        relationTo: 'pincodes';
        value: string | Pincode;
      } | null)
    | ({
        relationTo: 'counters';
        value: string | Counter;
      } | null)
    | ({
        relationTo: 'connector-configs';
        value: string | ConnectorConfig;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-domains';
        value: string | TenantDomain;
      } | null)
    | ({
        relationTo: 'plans';
        value: string | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'feature-flags';
        value: string | FeatureFlag;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  storeName?: T;
  themeColor?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  pwaIcon?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        address?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
        linkedin?: T;
      };
  grievanceOfficer?:
    | T
    | {
        name?: T;
        designation?: T;
        email?: T;
        phone?: T;
      };
  legalDefaults?:
    | T
    | {
        manufacturerName?: T;
        manufacturerAddress?: T;
        consumerCare?: T;
      };
  orderPrefix?: T;
  invoice?:
    | T
    | {
        prefix?: T;
        authorisedSignatory?: T;
        signature?: T;
        footerNote?: T;
      };
  checkout?:
    | T
    | {
        minOrderValue?: T | MoneySelect<T>;
        codEnabled?: T;
        codMinOrder?: T | MoneySelect<T>;
        codMaxOrder?: T | MoneySelect<T>;
        codFee?: T | MoneySelect<T>;
      };
  returns?:
    | T
    | {
        windowDays?: T;
        exchangeOnly?: T;
      };
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkUrl?: T;
      };
  policies?:
    | T
    | {
        shipping?: T;
        returns?: T;
        privacy?: T;
        terms?: T;
        warranty?: T;
      };
  seoDefaults?:
    | T
    | {
        titleTemplate?: T;
        ogImage?: T;
      };
  analytics?:
    | T
    | {
        ga4Id?: T;
        metaPixelId?: T;
        gtmId?: T;
      };
  maintenanceMode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Money_select".
 */
export interface MoneySelect<T extends boolean = true> {
  amountMinor?: T;
  currency?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  modelNumber?: T;
  primaryCategory?: T;
  categories?: T;
  brand?: T;
  shortDescription?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  description?: T;
  gallery?: T;
  videos?:
    | T
    | {
        url?: T;
        type?: T;
        id?: T;
      };
  attributes?: T;
  variants?: T;
  price?: T | MoneySelect<T>;
  compareAtPrice?: T | MoneySelect<T>;
  gstRate?: T;
  hsnCode?: T;
  weightGrams?: T;
  dimensions?:
    | T
    | {
        lengthMm?: T;
        widthMm?: T;
        heightMm?: T;
      };
  legal?:
    | T
    | {
        genericName?: T;
        netQuantity?: T;
        countryOfOrigin?: T;
        madeBy?: T;
        madeByName?: T;
        madeByAddress?: T;
        consumerCare?: T;
      };
  documents?: T;
  relatedProducts?: T;
  slug?: T;
  searchKeywords?: T;
  seo?: T | SeoSelect<T>;
  status?: T;
  purchaseMode?: T;
  isFeatured?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  tenant?: T;
  product?: T;
  options?: T;
  sku?: T;
  title?: T;
  barcode?: T;
  price?: T | MoneySelect<T>;
  compareAtPrice?: T | MoneySelect<T>;
  images?: T;
  stockQty?: T;
  reservedQty?: T;
  lowStockThreshold?: T;
  weightGrams?: T;
  allowBackorder?: T;
  status?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  attributeSet?: T;
  image?: T;
  banner?: T;
  description?: T;
  sizeChart?: T;
  isVisible?: T;
  sortOrder?: T;
  seo?: T | SeoSelect<T>;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-sets_select".
 */
export interface AttributeSetsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  attributes?:
    | T
    | {
        label?: T;
        code?: T;
        type?: T;
        unit?: T;
        group?: T;
        isFilterable?: T;
        isVariantAxis?: T;
        isComparable?: T;
        isRequired?: T;
        options?:
          | T
          | {
              label?: T;
              value?: T;
              swatchHex?: T;
              swatchImage?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-documents_select".
 */
export interface ProductDocumentsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  type?: T;
  file?: T;
  categories?: T;
  showOnDownloadsPage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        benefits?: T | BenefitsBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        brandStory?: T | BrandStoryBlockSelect<T>;
        productGrid?: T | ProductGridBlockSelect<T>;
        categoryTiles?: T | CategoryTilesBlockSelect<T>;
        downloads?: T | DownloadsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        imageText?: T | ImageTextBlockSelect<T>;
        video?: T | VideoBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        dealerFinder?: T | DealerFinderBlockSelect<T>;
        enquiryForm?: T | EnquiryFormBlockSelect<T>;
      };
  seo?: T | SeoSelect<T>;
  template?: T;
  slug?: T;
  publishedAt?: T;
  lastEditedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        mobileImage?: T;
        heading?: T;
        subheading?: T;
        buttonLabel?: T;
        buttonLink?: T | LinkSelect<T>;
        id?: T;
      };
  autoplay?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Link_select".
 */
export interface LinkSelect<T extends boolean = true> {
  type?: T;
  page?: T;
  category?: T;
  product?: T;
  url?: T;
  newTab?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  image?: T;
  mobileImage?: T;
  heading?: T;
  link?: T | LinkSelect<T>;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BenefitsBlock_select".
 */
export interface BenefitsBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        quote?: T;
        name?: T;
        place?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrandStoryBlock_select".
 */
export interface BrandStoryBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  image?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductGridBlock_select".
 */
export interface ProductGridBlockSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  category?: T;
  limit?: T;
  layout?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryTilesBlock_select".
 */
export interface CategoryTilesBlockSelect<T extends boolean = true> {
  heading?: T;
  categories?: T;
  style?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadsBlock_select".
 */
export interface DownloadsBlockSelect<T extends boolean = true> {
  heading?: T;
  documentType?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageTextBlock_select".
 */
export interface ImageTextBlockSelect<T extends boolean = true> {
  image?: T;
  heading?: T;
  text?: T;
  imageSide?: T;
  buttonLabel?: T;
  buttonLink?: T | LinkSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  heading?: T;
  youtubeUrl?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DealerFinderBlock_select".
 */
export interface DealerFinderBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  buttonLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EnquiryFormBlock_select".
 */
export interface EnquiryFormBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  enquiryType?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  header?:
    | T
    | {
        label?: T;
        link?: T | LinkSelect<T>;
        columns?:
          | T
          | {
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    link?: T | LinkSelect<T>;
                    id?: T;
                  };
              id?: T;
            };
        featuredImage?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              link?: T | LinkSelect<T>;
              id?: T;
            };
        id?: T;
      };
  mobileSameAsHeader?: T;
  mobile?:
    | T
    | {
        label?: T;
        link?: T | LinkSelect<T>;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  placement?: T;
  image?: T;
  mobileImage?: T;
  link?: T | LinkSelect<T>;
  startsAt?: T;
  endsAt?: T;
  priority?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dealers_select".
 */
export interface DealersSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  type?: T;
  isActive?: T;
  address?: T;
  city?: T;
  state?: T;
  pincode?: T;
  location?: T;
  phone?: T;
  email?: T;
  hours?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  tenant?: T;
  referenceNumber?: T;
  type?: T;
  status?: T;
  assignedTo?: T;
  productTitle?: T;
  modelNumber?: T;
  qty?: T;
  message?: T;
  name?: T;
  company?: T;
  phone?: T;
  email?: T;
  city?: T;
  pincode?: T;
  consentToContact?: T;
  internalNotes?:
    | T
    | {
        text?: T;
        by?: T;
        at?: T;
        id?: T;
      };
  source?:
    | T
    | {
        page?: T;
        utmSource?: T;
        utmMedium?: T;
        utmCampaign?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones_select".
 */
export interface ShippingZonesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  isServiceable?: T;
  sortOrder?: T;
  states?: T;
  pincodePrefixes?: T;
  rateType?: T;
  fee?: T | MoneySelect<T>;
  freeAbove?: T | MoneySelect<T>;
  baseWeightGrams?: T;
  perExtraKg?: T | MoneySelect<T>;
  valueBrackets?:
    | T
    | {
        from?: T | MoneySelect<T>;
        bracketFee?: T | MoneySelect<T>;
        id?: T;
      };
  codAllowed?: T;
  etaMinDays?: T;
  etaMaxDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  tenant?: T;
  orderNumber?: T;
  status?: T;
  paymentStatus?: T;
  fulfillmentStatus?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  items?:
    | T
    | {
        productId?: T;
        variantId?: T;
        sku?: T;
        title?: T;
        options?: T;
        imageUrl?: T;
        qty?: T;
        unitMinor?: T;
        mrpMinor?: T;
        discountMinor?: T;
        hsnCode?: T;
        gstRate?: T;
        taxableMinor?: T;
        cgstMinor?: T;
        sgstMinor?: T;
        igstMinor?: T;
        lineTotalMinor?: T;
        weightGrams?: T;
        id?: T;
      };
  charges?: T;
  totals?:
    | T
    | {
        itemsMinor?: T;
        discountMinor?: T;
        subtotalMinor?: T;
        shippingMinor?: T;
        codFeeMinor?: T;
        taxableMinor?: T;
        cgstMinor?: T;
        sgstMinor?: T;
        igstMinor?: T;
        taxMinor?: T;
        roundOffMinor?: T;
        grandTotalMinor?: T;
        paidMinor?: T;
        refundedMinor?: T;
      };
  shippingAddress?: T | ShopperAddressSelect<T>;
  billingSameAsShipping?: T;
  buyerGstin?: T;
  buyerLegalName?: T;
  billingAddress?: T | ShopperAddressSelect<T>;
  sellerStateCode?: T;
  placeOfSupplyStateCode?: T;
  paymentMethod?: T;
  paymentMode?: T;
  shippingMethod?:
    | T
    | {
        source?: T;
        zoneName?: T;
        courierName?: T;
        etaMinDays?: T;
        etaMaxDays?: T;
      };
  appliedOffers?:
    | T
    | {
        kind?: T;
        ref?: T;
        code?: T;
        name?: T;
        discountMinor?: T;
        id?: T;
      };
  couponCode?: T;
  invoice?: T;
  trackingCode?: T;
  whatsappOptIn?: T;
  notes?: T;
  source?: T;
  locale?: T;
  cartId?: T;
  placedAt?: T;
  confirmedAt?: T;
  paidAt?: T;
  completedAt?: T;
  cancelledAt?: T;
  expiresAt?: T;
  cancelReason?: T;
  stockState?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopperAddress_select".
 */
export interface ShopperAddressSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  line1?: T;
  line2?: T;
  landmark?: T;
  city?: T;
  stateCode?: T;
  pincode?: T;
  country?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-events_select".
 */
export interface OrderEventsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  type?: T;
  text?: T;
  from?: T;
  to?: T;
  byUser?: T;
  byLabel?: T;
  data?: T;
  at?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  provider?: T;
  mode?: T;
  providerOrderId?: T;
  providerPaymentId?: T;
  amountMinor?: T;
  status?: T;
  method?: T;
  methodDetail?: T;
  capturedAt?: T;
  failureReason?: T;
  refundedMinor?: T;
  processedEventIds?: T;
  raw?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  transaction?: T;
  amountMinor?: T;
  reason?: T;
  method?: T;
  providerRefundId?: T;
  reference?: T;
  status?: T;
  lines?: T;
  includesShipping?: T;
  creditNote?: T;
  by?: T;
  processedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  type?: T;
  number?: T;
  financialYear?: T;
  issuedAt?: T;
  againstInvoice?: T;
  seller?: T;
  buyer?: T;
  placeOfSupply?: T;
  lines?: T;
  totals?: T;
  amountInWords?: T;
  irn?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipments_select".
 */
export interface ShipmentsSelect<T extends boolean = true> {
  tenant?: T;
  order?: T;
  direction?: T;
  status?: T;
  items?:
    | T
    | {
        orderItemId?: T;
        title?: T;
        sku?: T;
        qty?: T;
        id?: T;
      };
  package?:
    | T
    | {
        lengthMm?: T;
        breadthMm?: T;
        heightMm?: T;
        weightGrams?: T;
      };
  provider?: T;
  carrier?: T;
  courierId?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  awb?: T;
  providerOrderId?: T;
  providerShipmentId?: T;
  labelUrl?: T;
  pickupScheduledFor?: T;
  expectedDeliveryDate?: T;
  codAmountMinor?: T;
  ewayBillNo?: T;
  attempts?: T;
  failureReason?: T;
  ndrAction?:
    | T
    | {
        action?: T;
        deferredDate?: T;
        note?: T;
        by?: T;
        at?: T;
      };
  events?:
    | T
    | {
        status?: T;
        at?: T;
        source?: T;
        by?: T;
        note?: T;
        location?: T;
        dedupeKey?: T;
        id?: T;
      };
  packedAt?: T;
  shippedAt?: T;
  outForDeliveryAt?: T;
  deliveredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  tenant?: T;
  tokenHash?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        qty?: T;
        addedAt?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  pincode?: T;
  shippingAddress?: T | ShopperAddressSelect<T>;
  couponCode?: T;
  lastActivityAt?: T;
  convertedOrder?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  tenant?: T;
  variant?: T;
  reason?: T;
  stockDelta?: T;
  reservedDelta?: T;
  order?: T;
  by?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "idempotency-keys_select".
 */
export interface IdempotencyKeysSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  route?: T;
  requestHash?: T;
  responseStatus?: T;
  responseBody?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pincodes_select".
 */
export interface PincodesSelect<T extends boolean = true> {
  pincode?: T;
  city?: T;
  district?: T;
  stateCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counters_select".
 */
export interface CountersSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connector-configs_select".
 */
export interface ConnectorConfigsSelect<T extends boolean = true> {
  tenant?: T;
  provider?: T;
  kind?: T;
  enabled?: T;
  mode?: T;
  publicConfig?: T;
  secretSealed?: T;
  savedSecrets?: T;
  webhookToken?: T;
  routingKey?: T;
  health?:
    | T
    | {
        lastTestAt?: T;
        lastTestOk?: T;
        lastTestMessage?: T;
        lastWebhookAt?: T;
        lastWebhookOkAt?: T;
        failingSince?: T;
        failedCount?: T;
        lastErrorAt?: T;
        lastError?: T;
        details?: T;
      };
  connectedBy?: T;
  connectedAt?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  gstin?: T;
  pan?: T;
  stateCode?: T;
  registeredAddress?: T | PostalAddressSelect<T>;
  industry?: T;
  supportEmail?: T;
  supportPhone?: T;
  whatsappNumber?: T;
  slug?: T;
  defaultLocale?: T;
  currency?: T;
  timezone?: T;
  enabledLocales?: T;
  notes?: T;
  status?: T;
  plan?: T;
  usage?:
    | T
    | {
        productsCount?: T;
        staffCount?: T;
        storageBytes?: T;
        ordersThisMonth?: T;
        updatedAt?: T;
      };
  enabledFeatures?: T;
  blockedConnectors?: T;
  dbRef?: T;
  createdBy?: T;
  activatedAt?: T;
  presetAppliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostalAddress_select".
 */
export interface PostalAddressSelect<T extends boolean = true> {
  line1?: T;
  line2?: T;
  city?: T;
  stateCode?: T;
  pincode?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-domains_select".
 */
export interface TenantDomainsSelect<T extends boolean = true> {
  host?: T;
  tenant?: T;
  type?: T;
  isPrimary?: T;
  redirectToPrimary?: T;
  verifiedAt?: T;
  sslStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  priceMonthly?: T | MoneySelect<T>;
  priceYearly?: T | MoneySelect<T>;
  introOffer?:
    | T
    | {
        price?: T | MoneySelect<T>;
        months?: T;
      };
  limits?:
    | T
    | {
        maxProducts?: T;
        maxStaffUsers?: T;
        maxStorageGB?: T;
        maxOrdersPerMonth?: T;
      };
  allowedModules?: T;
  allowedConnectors?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  tenant?: T;
  vendorName?: T;
  plan?: T;
  status?: T;
  billingCycle?: T;
  billingMode?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  trialEndsAt?: T;
  providerSubscriptionId?: T;
  payments?:
    | T
    | {
        amountMinor?: T;
        paidOn?: T;
        method?: T;
        reference?: T;
        coversPeriod?:
          | T
          | {
              start?: T;
              end?: T;
            };
        recordedBy?: T;
        id?: T;
      };
  history?:
    | T
    | {
        at?: T;
        event?: T;
        amountMinor?: T;
        reference?: T;
        by?: T;
        data?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  enabled?: T;
  config?: T;
  enabledBy?: T;
  enabledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  platformRole?: T;
  status?: T;
  lastLoginAt?: T;
  invitedBy?: T;
  invitedAt?: T;
  storeSession?:
    | T
    | {
        tenant?: T;
        mode?: T;
        reason?: T;
        startedAt?: T;
        endsAt?: T;
      };
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  actor?: T;
  actorRole?: T;
  action?: T;
  summary?: T;
  collectionSlug?: T;
  docId?: T;
  diff?: T;
  reason?: T;
  actingAsPlatform?: T;
  ip?: T;
  at?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTenancy-check-subscriptions".
 */
export interface TaskTenancyCheckSubscriptions {
  input?: unknown;
  output: {
    changed: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPayments-reconcile".
 */
export interface TaskPaymentsReconcile {
  input?: unknown;
  output: {
    settled: number;
    cancelled: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: string | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}