/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    'tenant-domains': TenantDomain;
    plans: Plan;
    subscriptions: Subscription;
    'feature-flags': FeatureFlag;
    users: User;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    'tenant-domains': TenantDomainsSelect<false> | TenantDomainsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'feature-flags': FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'tenancy-check-subscriptions': TaskTenancyCheckSubscriptions;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  name: string;
  legalName: string;
  /**
   * PAN and state fill in from the GSTIN
   */
  gstin?: string | null;
  /**
   * From the GSTIN when there is one
   */
  pan?: string | null;
  /**
   * Same state: CGST + SGST. Other states: IGST
   */
  stateCode?:
    | (
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '26'
        | '27'
        | '29'
        | '30'
        | '31'
        | '32'
        | '33'
        | '34'
        | '35'
        | '36'
        | '37'
        | '38'
        | '97'
        | '01'
        | '02'
        | '03'
        | '04'
        | '05'
        | '06'
        | '07'
        | '08'
        | '09'
      )
    | null;
  registeredAddress?: PostalAddress;
  industry: ('sanitary' | 'locks' | 'hardware' | 'decor' | 'clothing' | 'other')[];
  supportEmail?: string | null;
  supportPhone?: string | null;
  whatsappNumber?: string | null;
  /**
   * Permanent. Names the subdomain and the vendor UI folder in code (src/storefront/vendors/<slug>).
   */
  slug: string;
  /**
   * More languages in Phase 2
   */
  defaultLocale?: 'en' | null;
  /**
   * Fixed to INR in the MVP
   */
  currency?: 'INR' | null;
  timezone?: 'Asia/Kolkata' | null;
  enabledLocales?: 'en'[] | null;
  /**
   * Visible to our team only. For example: prefers WhatsApp, renewal call in March.
   */
  notes?: string | null;
  /**
   * Changed with Go live, Suspend and Resume above
   */
  status: 'draft' | 'active' | 'suspended' | 'archived';
  /**
   * Changed from the Billing tab
   */
  plan: string | Plan;
  usage?: {
    productsCount?: number | null;
    staffCount?: number | null;
    storageBytes?: number | null;
    ordersThisMonth?: number | null;
    updatedAt?: string | null;
  };
  dbRef?: string | null;
  createdBy?: (string | null) | User;
  activatedAt?: string | null;
  presetAppliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostalAddress".
 */
export interface PostalAddress {
  line1?: string | null;
  line2?: string | null;
  city?: string | null;
  stateCode?:
    | (
        | '10'
        | '11'
        | '12'
        | '13'
        | '14'
        | '15'
        | '16'
        | '17'
        | '18'
        | '19'
        | '20'
        | '21'
        | '22'
        | '23'
        | '24'
        | '26'
        | '27'
        | '29'
        | '30'
        | '31'
        | '32'
        | '33'
        | '34'
        | '35'
        | '36'
        | '37'
        | '38'
        | '97'
        | '01'
        | '02'
        | '03'
        | '04'
        | '05'
        | '06'
        | '07'
        | '08'
        | '09'
      )
    | null;
  pincode?: string | null;
}
/**
 * A plan is a ceiling, not a switch: features in a plan stay off until switched on per vendor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: string;
  name: string;
  /**
   * Short permanent key, for example growth
   */
  code: string;
  priceMonthly: Money;
  priceYearly: Money;
  /**
   * Checked on the server. Stores are warned at 90% of a limit.
   */
  limits: {
    maxProducts: number;
    maxStaffUsers: number;
    maxStorageGB: number;
    /**
     * Empty means no limit
     */
    maxOrdersPerMonth?: number | null;
  };
  allowedModules?:
    | (
        | 'guest-checkout'
        | 'cod-confirmation'
        | 'cod'
        | 'enquiries'
        | 'appointments'
        | 'enquire-only-products'
        | 'downloads'
        | 'size-guide'
        | 'product-videos'
        | 'compare'
        | 'dealer-locator'
        | 'whatsapp-button'
        | 'multilingual'
        | 'lookbook'
        | 'blog'
        | 'pincode-check'
        | 'schemes'
        | 'coupons'
        | 'trade-schemes'
        | 'wishlist'
        | 'reviews'
        | 'offer-messages'
        | 'whatsapp-offers'
        | 'push-notifications'
        | 'abandoned-cart'
        | 'affiliate'
        | 'warranty'
        | 'service-requests'
        | 'installation-booking'
        | 'spare-parts'
        | 'b2b'
        | 'loyalty'
      )[]
    | null;
  allowedConnectors?: ('razorpay' | 'manual' | 'shiprocket' | 'meta-whatsapp' | 'msg91')[] | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Money".
 */
export interface Money {
  amountMinor?: number | null;
  currency: 'INR';
}
/**
 * Everyone who signs in to the admin: our team and every store’s staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  phone?: string | null;
  /**
   * Our team only. Leave empty for vendor staff.
   */
  platformRole?: ('super-admin' | 'support') | null;
  status: 'invited' | 'active' | 'disabled';
  lastLoginAt?: string | null;
  invitedBy?: (string | null) | User;
  invitedAt?: string | null;
  tenants?:
    | {
        tenant: string | Tenant;
        roles: ('owner' | 'manager' | 'catalog-editor' | 'order-manager' | 'content-editor' | 'support')[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  hasAPIKey?: boolean | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-domains".
 */
export interface TenantDomain {
  id: string;
  host: string;
  tenant: string | Tenant;
  type: 'subdomain' | 'custom';
  isPrimary?: boolean | null;
  /**
   * Send visitors on this host to the primary domain (301)
   */
  redirectToPrimary?: boolean | null;
  verifiedAt?: string | null;
  sslStatus?: ('pending' | 'issuing' | 'active' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manual billing in the MVP (automatic with Razorpay Subscriptions in Phase 2).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  tenant: string | Tenant;
  vendorName?: string | null;
  plan: string | Plan;
  status: 'trialing' | 'active' | 'past_due' | 'cancelled' | 'paused';
  billingCycle: 'monthly' | 'yearly';
  billingMode: 'manual' | 'razorpay';
  currentPeriodStart?: string | null;
  currentPeriodEnd?: string | null;
  trialEndsAt?: string | null;
  providerSubscriptionId?: string | null;
  payments?:
    | {
        amountMinor: number;
        paidOn: string;
        method: 'neft' | 'imps' | 'upi' | 'cheque' | 'card';
        reference?: string | null;
        coversPeriod?: {
          start?: string | null;
          end?: string | null;
        };
        recordedBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  history?:
    | {
        at: string;
        event: string;
        amountMinor?: number | null;
        reference?: string | null;
        by?: (string | null) | User;
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags".
 */
export interface FeatureFlag {
  id: string;
  tenant?: (string | null) | Tenant;
  key:
    | 'guest-checkout'
    | 'cod-confirmation'
    | 'cod'
    | 'enquiries'
    | 'appointments'
    | 'enquire-only-products'
    | 'downloads'
    | 'size-guide'
    | 'product-videos'
    | 'compare'
    | 'dealer-locator'
    | 'whatsapp-button'
    | 'multilingual'
    | 'lookbook'
    | 'blog'
    | 'pincode-check'
    | 'schemes'
    | 'coupons'
    | 'trade-schemes'
    | 'wishlist'
    | 'reviews'
    | 'offer-messages'
    | 'whatsapp-offers'
    | 'push-notifications'
    | 'abandoned-cart'
    | 'affiliate'
    | 'warranty'
    | 'service-requests'
    | 'installation-booking'
    | 'spare-parts'
    | 'b2b'
    | 'loyalty';
  enabled?: boolean | null;
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  enabledBy?: (string | null) | User;
  enabledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  tenant?: (string | null) | Tenant;
  actor?: (string | null) | User;
  actorRole?: string | null;
  action:
    | 'support_access'
    | 'store_created'
    | 'store_status_changed'
    | 'feature_changed'
    | 'connector_changed'
    | 'plan_changed'
    | 'plan_edited'
    | 'subscription_payment'
    | 'subscription_status_changed'
    | 'staff_invited'
    | 'staff_changed'
    | 'two_factor_reset'
    | 'domain_changed'
    | 'price_changed'
    | 'refund'
    | 'scheme_changed'
    | 'coupon_changed'
    | 'commission_changed'
    | 'affiliate_payout'
    | 'review_moderated';
  /**
   * One line people can read
   */
  summary?: string | null;
  collectionSlug?: string | null;
  docId?: string | null;
  diff?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  reason?: string | null;
  actingAsPlatform?: boolean | null;
  ip?: string | null;
  at: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'tenancy-check-subscriptions';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'tenancy-check-subscriptions') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'tenant-domains';
        value: string | TenantDomain;
      } | null)
    | ({
        relationTo: 'plans';
        value: string | Plan;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'feature-flags';
        value: string | FeatureFlag;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  gstin?: T;
  pan?: T;
  stateCode?: T;
  registeredAddress?: T | PostalAddressSelect<T>;
  industry?: T;
  supportEmail?: T;
  supportPhone?: T;
  whatsappNumber?: T;
  slug?: T;
  defaultLocale?: T;
  currency?: T;
  timezone?: T;
  enabledLocales?: T;
  notes?: T;
  status?: T;
  plan?: T;
  usage?:
    | T
    | {
        productsCount?: T;
        staffCount?: T;
        storageBytes?: T;
        ordersThisMonth?: T;
        updatedAt?: T;
      };
  dbRef?: T;
  createdBy?: T;
  activatedAt?: T;
  presetAppliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostalAddress_select".
 */
export interface PostalAddressSelect<T extends boolean = true> {
  line1?: T;
  line2?: T;
  city?: T;
  stateCode?: T;
  pincode?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-domains_select".
 */
export interface TenantDomainsSelect<T extends boolean = true> {
  host?: T;
  tenant?: T;
  type?: T;
  isPrimary?: T;
  redirectToPrimary?: T;
  verifiedAt?: T;
  sslStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  priceMonthly?: T | MoneySelect<T>;
  priceYearly?: T | MoneySelect<T>;
  limits?:
    | T
    | {
        maxProducts?: T;
        maxStaffUsers?: T;
        maxStorageGB?: T;
        maxOrdersPerMonth?: T;
      };
  allowedModules?: T;
  allowedConnectors?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Money_select".
 */
export interface MoneySelect<T extends boolean = true> {
  amountMinor?: T;
  currency?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  tenant?: T;
  vendorName?: T;
  plan?: T;
  status?: T;
  billingCycle?: T;
  billingMode?: T;
  currentPeriodStart?: T;
  currentPeriodEnd?: T;
  trialEndsAt?: T;
  providerSubscriptionId?: T;
  payments?:
    | T
    | {
        amountMinor?: T;
        paidOn?: T;
        method?: T;
        reference?: T;
        coversPeriod?:
          | T
          | {
              start?: T;
              end?: T;
            };
        recordedBy?: T;
        id?: T;
      };
  history?:
    | T
    | {
        at?: T;
        event?: T;
        amountMinor?: T;
        reference?: T;
        by?: T;
        data?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feature-flags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  tenant?: T;
  key?: T;
  enabled?: T;
  config?: T;
  enabledBy?: T;
  enabledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  platformRole?: T;
  status?: T;
  lastLoginAt?: T;
  invitedBy?: T;
  invitedAt?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        roles?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  hasAPIKey?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  tenant?: T;
  actor?: T;
  actorRole?: T;
  action?: T;
  summary?: T;
  collectionSlug?: T;
  docId?: T;
  diff?: T;
  reason?: T;
  actingAsPlatform?: T;
  ip?: T;
  at?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskTenancy-check-subscriptions".
 */
export interface TaskTenancyCheckSubscriptions {
  input?: unknown;
  output: {
    changed: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}